"""
Reply language detection — Urdu script + Roman Urdu (Pakistani style).
Roman Urdu ko mazboot pakarna; seedha English FAQ (what/how/...) bina Urdu cue ke English.
"""

import re

# Arabic + Arabic Presentation Forms-B + common Urdu blocks
URDU_SCRIPT = re.compile(r"[\u0600-\u06FF\u0750-\u077F\uFB50-\uFDFF\uFE70-\uFEFF]")

# Aksar Roman Urdu sawalon mein yeh milte hain; English line mein kam
_INSTANT_URDU = frozenset(
    {
        "kya",
        "hai",
        "hain",
        "ho",
        "hon",
        "hongay",
        "hogi",
        "hoga",
        "hongi",
        "kaise",
        "kaisa",
        "kaisi",
        "kaunsi",
        "kaunsa",
        "kaunse",
        "konsa",
        "konsi",
        "konse",
        "kab",
        "kahan",
        "kidhar",
        "kyun",
        "kyoon",
        "kiyun",
        "kitna",
        "kitni",
        "kitne",
        "mujhe",
        "humain",
        "hamain",
        "apko",
        "aapko",
        "tumhe",
        "tumhain",
        "chahiye",
        "chahta",
        "chahti",
        "chahtay",
        "chahte",
        "nahi",
        "nahin",
        "batao",
        "bataiye",
        "batayein",
        "batain",
        "bataen",
        "dijiye",
        "suniye",
        "meherbani",
        "shukriya",
        "zara",
        "zaroor",
        "zaroori",
        "bilkul",
        "theek",
        "thaik",
        "acha",
        "accha",
        "achhi",
        "sir",
        "madam",
        "janab",
        "sahab",
        "sahib",
        "magar",
        "lekin",
        "warna",
        "waise",
        "phir",
        "agar",
        "toh",
        "tou",
        "kyunke",
        "kyunkay",
        "taake",
        "taakay",
        "poochen",
        "poochon",
        "pooch",
        "poch",
        "maloom",
        "maaloom",
        "silselay",
        "silsile",
        "hawalay",
        "hawale",
        "mutaliq",
        "mutaliqa",
        "maloomat",
        "maaloomat",
        "tafteesh",
        "tainati",
        "qabil",
        "layiq",
        "mustahiq",
        "adaigi",
        "akhri",
        "akhiri",
        "pehlay",
        "pehle",
        "dobara",
        "phirse",
        "abhi",
        "filhal",
        "parsoun",
        "waqt",
        "tarikh",
        "taareekh",
        "imtehan",
        "dakhlay",
        "dakhla",
        "daakhla",
        "aitmayad",
        "etimaad",
        "rusoobat",
        "rabta",
        "rabte",
        "nambar",
        "muqaam",
        "hostal",
        "wazan",
        "marit",
        "meraat",
        "fohir",
        "soorat",
        "surat",
        "haalat",
        "sawal",
        "sawaal",
        "jwaab",
        "jawab",
        "madadgar",
        "foori",
        "fori",
        "fauri",
        "qareeb",
        "door",
        "thori",
        "ziada",
        "bohat",
        "bohut",
        "bht",
        "kafi",
        "mukammal",
        "mukamal",
        "malomat",
        "malomaat",
        "tamam",
        "poori",
        "pura",
        "poora",
        "unviristi",
        "yuniversity",
        "smester",
    }
)

# Grammar + Roman Urdu mix (English spellings jaise "fee", "campus" yahan NAHI)
_ROMAN_URDU_HINTS = frozenset(
    {
        "kya",
        "hai",
        "hain",
        "mujhe",
        "mera",
        "meri",
        "meray",
        "mere",
        "humara",
        "hamara",
        "humari",
        "hamari",
        "humain",
        "hamain",
        "aap",
        "ap",
        "apka",
        "apki",
        "apke",
        "unka",
        "unki",
        "unke",
        "kaise",
        "kaisa",
        "kaisi",
        "kahan",
        "kab",
        "kyun",
        "kyoon",
        "kaun",
        "kitna",
        "kitni",
        "kitne",
        "chahiye",
        "chahta",
        "chahti",
        "chahte",
        "chahtay",
        "batao",
        "bata",
        "bataiye",
        "nahi",
        "nahin",
        "hoga",
        "hogi",
        "hongay",
        "hongi",
        "wala",
        "wali",
        "walay",
        "waley",
        "walon",
        "walo",
        "mein",
        "mean",
        "se",
        "say",
        "ko",
        "ne",
        "par",
        "pe",
        "pay",
        "tak",
        "aur",
        "ya",
        "lekin",
        "magar",
        "phir",
        "toh",
        "tou",
        "shukriya",
        "shukria",
        "meherbani",
        "janab",
        "sahib",
        "sahab",
        "karo",
        "karna",
        "karein",
        "karen",
        "karain",
        "karoon",
        "karta",
        "karti",
        "kartay",
        "karte",
        "dena",
        "dein",
        "diye",
        "dijiye",
        "batana",
        "samjhao",
        "samjhain",
        "hona",
        "hoti",
        "hota",
        "honay",
        "hone",
        "tha",
        "thi",
        "woh",
        "wo",
        "yeh",
        "ye",
        "bhi",
        "sirf",
        "bas",
        "abhi",
        "agar",
        "poochen",
        "pooch",
        "madad",
        "batayein",
        "suniye",
        "sunain",
        "dekho",
        "dekhein",
        "ke",
        "ki",
        "ka",
        "ku",
        "bare",
        "baare",
        "mutaliq",
        "mutaliqa",
        "maloomat",
        "maaloomat",
        "hawalay",
        "hawale",
        "silselay",
        "silsile",
        "batain",
        "bataen",
        "lijiye",
        "milegi",
        "milega",
        "milenge",
        "milti",
        "milta",
        "milte",
        "jana",
        "jaanna",
        "jaana",
        "samjha",
        "samjhai",
        "samajh",
        "rakhti",
        "rakhta",
        "rakhte",
        "deti",
        "deta",
        "detay",
        "lete",
        "letay",
        "laitay",
        "lena",
        "lenay",
        "denay",
        "banay",
        "bani",
        "bana",
        "banega",
        "hun",
        "ho",
        "hon",
        "hoon",
        "mahina",
        "mahinay",
        "din",
        "waqt",
        "tarikh",
        "taareekh",
        "jaisa",
        "jaisi",
        "jaise",
        "warna",
        "waise",
        "tab",
        "kyunke",
        "kyunkay",
        "taake",
        "taakay",
        "kidhar",
        "dars",
        "namoon",
        "namon",
        "iltija",
        "guzarish",
        "sb",
        "sab",
        "kam",
        "poochen",
        "poochon",
        "kiyun",
        "kaunsi",
        "kaunsa",
        "kaunse",
        "konsa",
        "konsi",
        "konse",
        "zara",
        "zaroor",
        "bilkul",
        "theek",
        "thaik",
        "acha",
        "accha",
        "achhi",
        "maloom",
        "maaloom",
        "tafteesh",
        "dakhlay",
        "dakhla",
        "daakhla",
        "rabta",
        "rabte",
        "nambar",
        "muqaam",
        "hostal",
        "sawal",
        "sawaal",
        "jwaab",
        "jawab",
        "foori",
        "fori",
        "fauri",
        "qareeb",
        "door",
        "thori",
        "ziada",
        "bohat",
        "bohut",
        "bht",
        "kafi",
        "mukammal",
        "mukamal",
        "malomat",
        "malomaat",
        "tamam",
        "poori",
        "pura",
        "poora",
        "unviristi",
        "yuniversity",
        "smester",
        "imtehan",
        "akhri",
        "akhiri",
        "pehlay",
        "pehle",
        "dobara",
        "phirse",
        "filhal",
        "parsoun",
    }
)

_ROMAN_URDU_HINTS |= _INSTANT_URDU

_EZAFE = re.compile(r"\b(ke|ki|ku)\s+[a-z]{2,}", re.I)
_EZAFE_REV = re.compile(r"\b[a-z]{2,}\s+(ki|ka|ke|ku)\s+[a-z]{2,}", re.I)
_KE_BARE = re.compile(r"\bke\s+bare\b|\bbaare\b|\bmutaliq\b|\bmutaliqa\b|\bhawalay\b|\bhawale\b", re.I)

_QUESTION_TAIL_URDU = re.compile(
    r"\b(?:hai|hain|ho|hongi|hoga|hogi|chahiye|karna|karoon|karain|karein|tha|thi)\s*[?.!…]*\s*$",
    re.I,
)

_ENGLISH_LEADING = re.compile(
    r"^\s*(?:what|when|where|which|who|whom|whose|why|how)\b"
    r"|^\s*(?:please|could|would|can|tell\s+me|i\s+(?:want|need|would|am)|we\s+want|do\s+you|is\s+there|are\s+there)\b",
    re.I,
)


def detect_reply_language(text: str) -> str:
    """
    Return 'ur' for Urdu script or Roman Urdu; otherwise 'en'.
    """
    if not text or not text.strip():
        return "en"

    if URDU_SCRIPT.search(text):
        return "ur"

    lower = text.strip().lower()
    words = re.findall(r"[a-zA-Z]+", lower)
    if not words:
        return "en"

    if any(w in _INSTANT_URDU for w in words):
        return "ur"

    urdu_hits = sum(1 for w in words if w in _ROMAN_URDU_HINTS)

    structural = 0
    if _EZAFE.search(lower) or _EZAFE_REV.search(lower):
        structural += 3
    if _KE_BARE.search(lower):
        structural += 2
    if _QUESTION_TAIL_URDU.search(lower):
        structural += 2

    score = urdu_hits + structural
    ratio = urdu_hits / len(words) if words else 0.0

    if score >= 2 or ratio >= 0.18:
        return "ur"
    if len(words) <= 8 and score >= 1:
        return "ur"
    if urdu_hits >= 1 and ratio >= 0.12:
        return "ur"

    if _ENGLISH_LEADING.search(lower) and urdu_hits == 0 and structural == 0:
        return "en"

    if score >= 1:
        return "ur"

    return "en"
